# Generated by Django 4.0.5 on 2022-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_test_user_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_user',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
