# Generated by Django 4.0.5 on 2022-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice_picks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='picks',
            field=models.ManyToManyField(to='quiz.test_user'),
        ),
    ]
