# Generated by Django 4.0.5 on 2022-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_choice_picks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='picks',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.test_user'),
        ),
    ]
